import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("admin shops workspace is protected, grouped by business, and server-paginated", async () => {
  const route = await readFile(path.join(root, "app/api/admin/shops/route.js"), "utf8");
  const directory = await readFile(path.join(root, "components/admin/ShopDirectoryPanel.jsx"), "utf8");
  const details = await readFile(path.join(root, "components/admin/ShopDetailsPanel.jsx"), "utf8");
  const routePage = await readFile(path.join(root, "app/admin/shops/page.jsx"), "utf8");
  const detailPage = await readFile(path.join(root, "app/admin/shops/[id]/page.jsx"), "utf8");
  const detailApi = await readFile(path.join(root, "app/api/admin/shops/[id]/route.js"), "utf8");
  const sidebar = await readFile(path.join(root, "components/admin/AdminSidebar.jsx"), "utf8");

  assert.match(route, /requireAdmin\(request\)/);
  assert.match(route, /from\("businesses"\)/);
  assert.match(route, /business_id/);
  assert.match(route, /SHOP_PAGE_SIZE = 15/);
  assert.match(route, /REVIEW_PAGE_SIZE = 10/);
  assert.match(route, /CATEGORY_PAGE_SIZE = 10/);
  assert.match(route, /SERVICE_PAGE_SIZE = 10/);
  assert.match(route, /MAX_SERVICE_ROWS/);
  assert.match(route, /service_pricing_rules/);
  assert.match(route, /serviceCount/);
  assert.match(route, /selectedShopId/);
  assert.match(route, /totalReviewCount/);
  assert.match(route, /pendingCategoryCount/);
  assert.match(route, /export async function PATCH/);
  assert.match(route, /action === "REVIEW"/);
  assert.match(route, /action === "CATEGORY"/);
  assert.match(directory, /Search shops or owners/);
  assert.match(directory, /href={`\/admin\/shops\/\$\{shop\.shopId\}`}/);
  assert.match(directory, /15 per page/);
  assert.match(directory, /No matching shops/);
  assert.doesNotMatch(directory, /latestPendingProfileChange/);
  assert.doesNotMatch(directory, /Profile change pending/);
  assert.match(directory, /max-w-\[1600px\]/);
  assert.match(details, /Overview/);
  assert.match(details, /Services/);
  assert.match(details, /Category Approvals/);
  assert.match(details, /No reviews yet/);
  assert.match(details, /No category approvals yet/);
  assert.match(details, /No services yet/);
  assert.match(details, /Back to shop list/);
  assert.match(details, /shopId/);
  assert.match(details, /updateReviewVisibility/);
  assert.match(details, /updateCategoryStatus/);
  assert.doesNotMatch(details, /Profile change requests/);
  assert.doesNotMatch(details, /updateProfileChangeRequest/);
  assert.doesNotMatch(details, /api\/admin\/verifications/);
  assert.match(details, /servicePagination/);
  assert.match(details, /max-w-\[1600px\]/);
  assert.match(routePage, /ShopDirectoryPanel/);
  assert.match(detailPage, /ShopDetailsPanel/);
  assert.match(detailPage, /useParams/);
  assert.match(detailApi, /getShopDirectory/);
  assert.match(sidebar, /href: "\/admin\/shops"/);
});
